Added lobotomise code, test targets, renamed the morphology cases.

diff --git a/run-expr b/run-expr
--- a/run-expr
+++ b/run-expr
@@ -1,17 +1,41 @@
 #!/bin/bash
 # run-expr
 
+usage()
+{
+    echo "usage: run-expr [-f] [-c count] <experiment name> [results-dir]" >&2;
+}
+
 if [ $# -ne 1 ] && [ $# -ne 2 ]; then
-    echo "usage: run-expr <experiment name> [results-dir]" >&2;
+    usage;
     exit 2;
 fi
+
+force=0;
+count=3;
+while getopts hfc: opt; do
+	case $opt in
+	    f) force=1;;
+        h) usage;;
+	    c) count=$OPTARG;;
+	    *) echo "error: invalid option given." >&2; usage;;
+	esac
+done
+shift $[ OPTIND - 1 ]
+
+
 expName="$1";
-count=1;
 resultsDir=".";
 if [ $# -eq 2 ]; then
     resultsDir="$2";
 fi
 mkdir -p "$resultsDir/$expName";
 for ((i = 1; i <= $count; i++)); do 
-    alps_frog "$expName" "$resultsDir/$expName/$i.pop" | tee "$resultsDir/$expName/$i.out"
+    # Add a check to not overwrite currently existing results?
+    outfile="$resultsDir/$expName/$i.out"
+    if [ "$force" -eq 1 ] && [ -f "$outfile"  ]; then
+        echo "warning: '$outfile' already exists; skipping." >&2;
+    else
+        alps_main "$expName" "$resultsDir/$expName/$i" | tee "$outfile"
+    fi
 done
diff --git a/run-expr-all b/run-expr-all
--- a/run-expr-all
+++ b/run-expr-all
@@ -1,12 +1,26 @@
 #!/bin/bash
 # run-expr-all
 
+usage()
+{
+   echo "usage: run-expr-all [-c count] <results-name>" >&2;
+}
 if [ $# -ne 1 ]; then
-    echo "usage: run-expr-all <results-name>" >&2;
+    usage;
     exit 2;
 fi
 
+count=1;
+while getopts hfc: opt; do
+	case $opt in
+	    f) force=1;;
+        h) usage;;
+	    c) count=$OPTARG;;
+	    *) echo "error: invalid option given." >&2; usage;;
+	esac
+done
+shift $[ OPTIND - 1 ]
 
-for exp in 0 1 Ap Ao Bp Bo; do 
-    run-expr $exp "$1"
+for exp in An Bn Ap Bp Ao Bo; do
+    run-expr -c $count $exp "$1"
 done
