Implemented an adaptive RK integrator.

diff --git a/run-expr b/run-expr
--- a/run-expr
+++ b/run-expr
@@ -41,6 +41,9 @@ for ((i = $num; i < ($num + $count); i++)); do
     if [ "$force" -eq 1 ] && [ -f "$outfile"  ]; then
         echo "warning: '$outfile' already exists; skipping." >&2;
     else
-        alps_main "$expName" "$targetIndex" "$lobotomise" "$dir/pop-phase" | tee "$outfile"
+        if ! alps_main "$expName" "$targetIndex" "$lobotomise" "$dir/pop-phase" | tee "$outfile"; then
+            echo "error: alps_main failed with exit code ${PIPESTATUS}" >&2;
+            exit 1;
+        fi
     fi
 done
diff --git a/run-expr-all b/run-expr-all
--- a/run-expr-all
+++ b/run-expr-all
@@ -27,7 +27,10 @@ fi
 for target in 1 2 3 4; do 
     for lobotomise in 0 1; do
         for exp in Bo An Bn Ap Bp Ao; do
-            run-expr -n $num -c $count -d "$1" $exp $target $lobotomise
+            if ! run-expr -n $num -c $count -d "$1" $exp $target $lobotomise; then
+                echo "error: run-expr exited with error code ${PIPESTATUS}" >&2;
+                exit 1;
+            fi
         done
     done
 done
